import crypto from 'node:crypto';
import { Wallet, SigningKey } from 'ethers';

/**
 * Byte-for-byte port of the BlindMarket brief crypto, as generated by the
 * "Use from your agent" script (frontend/src/components/UseFromAgentModal.tsx
 * buildScript) and implemented identically in frontend/src/lib/crypto.ts and
 * backend/src/services/crypto.ts. Do not change wire formats:
 *   AES-256-GCM: [12-byte IV][16-byte auth tag][ciphertext]
 *   ECIES(secp256k1): [65-byte uncompressed ephemeral pubkey][AES-GCM blob]
 *     AES key = HKDF-SHA256(ECDH shared X, salt=empty, info='BlindMarket-ECIES-v1')
 */

export function generateAesKey(): Buffer {
  return crypto.randomBytes(32);
}

export function aesEncrypt(plain: Buffer, key: Buffer): Buffer {
  const iv = crypto.randomBytes(12);
  const c = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ct = Buffer.concat([c.update(plain), c.final()]);
  return Buffer.concat([iv, c.getAuthTag(), ct]);
}

export function eciesEncrypt(payload: Buffer, recipientPubHex: string): Buffer {
  const pub = recipientPubHex.startsWith('0x') ? recipientPubHex.slice(2) : recipientPubHex;
  const eph = Wallet.createRandom();
  const shared = new SigningKey(eph.privateKey).computeSharedSecret('0x' + pub);
  const sharedX = Buffer.from(shared.slice(4, 68), 'hex'); // drop 0x04 prefix, keep X
  const aesKey = Buffer.from(crypto.hkdfSync('sha256', sharedX, Buffer.alloc(0), 'BlindMarket-ECIES-v1', 32));
  const ephPub = Buffer.from(SigningKey.computePublicKey(eph.privateKey, false).slice(2), 'hex');
  return Buffer.concat([ephPub, aesEncrypt(payload, aesKey)]);
}

export function sha256Hex(data: Buffer): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}
